#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
TIMES="10"
domain=$(cat /etc/xray/domain)
CHATID="848676"
KEY="764548:AAGSQ6hq7OHUi521jxUcgbMFYp8"
URL="https://api.telegram.org/bot$KEY/sendMessage"
CITY=$(cat /etc/xray/city)
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e "\e[42m         Add Xray/Vmess Account          \E[0m"
  echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

  read -rp "User: " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[42m         Add Xray/Vmess Account          \E[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
  fi
done


# Array berisi pilihan browser
brow=(chrome firefox edge safari)
# Pilih elemen secara random dari array
browser=${brow[$RANDOM % ${#brow[@]}]}

ani=("one-piece" "naruto-shippuden" "attack-on-titan" "demon-slayer" "death-note" "jujutsu-kaisen" "one-punch-man" "dragon-ball" "bleach" "uzumaki" "blue-lock" "wand-and-sword" "solo-leveling" "wind-breaker" "look-back")
# Pilih elemen secara random dari array
anime=${ani[$RANDOM % ${#ani[@]}]}

uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
clear
VMESS_WS=`cat<<EOF
      {
      "v": "2",
      "ps": "$user-$browser",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/play/anime/$anime",
      "type": "none",
      "host": "${domain}",
      "tls": "tls",
      "fp": "${browser}"
}
EOF`
VMESS_NON_TLS=`cat<<EOF
      {
      "v": "2",
      "ps": "$user-$browser",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/play/anime/$anime",
      "type": "none",
      "host": "${domain}",
      "tls": "none",
      "fp": "${browser}"
}
EOF`
VMESS_GRPC=`cat<<EOF
      {
      "v": "2",
      "ps": "$user-$browser",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls",
      "fp": "${browser}"
}
EOF`
vmesslink1="vmess://$(echo $VMESS_WS | base64 -w 0)"
vmesslink2="vmess://$(echo $VMESS_NON_TLS | base64 -w 0)"
vmesslink3="vmess://$(echo $VMESS_GRPC | base64 -w 0)"

cat >/var/www/html/vmess-$user.txt <<-END
───────────────────
         Add Xray/Vmess Account
───────────────────
Remarks     : $user
Domain      : $domain
Port Tls    : 443
Port Ntls   : 80
Encryption  : none
Path        : "/play/anime/$anime"
ServiceName : vmess-grpc
Expired On  : $exp
───────────────────
TLS Link: $vmesslink1
───────────────────
Non-TLS Link: $vmesslink2
───────────────────
GRPC Link: $vmesslink3
───────────────────
END
# Output Informasi Akun
echo -e "───────────────────"
echo -e "         Add Xray/Vmess Account"
echo -e "───────────────────"
echo -e "Remarks     : $user"
echo -e "Domain      : $domain"
echo -e "Port Tls    : 443"
echo -e "Port Ntls   : 80"
echo -e "Encryption  : none"
echo -e "Path        : /play/anime/$anime"
echo -e "ServiceName : vmess-grpc"
echo -e "Expired On  : $exp"
echo -e "───────────────────"
echo -e "TLS Link: $vmesslink1"
echo -e "───────────────────"
echo -e "Non-TLS Link: $vmesslink2"
echo -e "───────────────────"
echo -e "GRPC Link: $vmesslink3"
echo -e "───────────────────"
TEXT="
<code>───────────────────────────</code>
<code>    Xray/Vmess Account</code>
<code>───────────────────────────</code>
<code>Remarks      : ${user}</code>
<code>Domain       : ${domain}</code>
<code>Location     : $CITY</code>
<code>Port TLS     : 443</code>
<code>Port DNS     : 443, 53</code>
<code>Port NTLS    : 80, 8080, 2086</code>
<code>Port GRPC    : 443</code>
<code>User ID      : ${uuid}</code>
<code>AlterId      : 0</code>
<code>Security     : auto</code>
<code>Network      : WS or gRPC</code>
<code>Path TLS     : (/play/anime/$anime)</code>
<code>Path Dynamic : CF-XRAY:http://bug.com</code>
<code>ServiceName  : vmess-grpc</code>
<code>───────────────────────────</code>
<code>Link TLS     :</code> 
<code>${vmesslink1}</code>
<code>───────────────────────────</code>
<code>Link NTLS    :</code> 
<code>${vmesslink2}</code>
<code>───────────────────────────</code>
<code>Link GRPC    :</code> 
<code>${vmesslink3}</code>
<code>───────────────────────────</code>
<code>Format OpenClash :</code> http://${domain}:81/vmess-$user.txt
<code>───────────────────────────</code>
<code>Expired On : $exp</code>
"
systemctl restart xray
#systemctl restart nginx
service cron restart

curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
read -n 1 -s -r -p "Press any key to back on menu"
menu
